version: 0.0
os: linux
files:
  - source: artifacts/themes/
    destination: /var/www/html/wordpress/wp-content/themes/
    overwrite: yes

hooks:
  BeforeInstall:
    - location: scripts/stop_apache.sh
      timeout: 60
      runas: root

  AfterInstall:
    - location: scripts/permissions.sh
      timeout: 60
      runas: root

  ApplicationStart:
    - location: scripts/restart_apache.sh
      timeout: 60
      runas: root