version: 0.0
os: linux
files:
  - source: wp-content/themes/
    destination: /var/www/html/wordpress/wp-content/themes/

permissions:
  - object: /var/www/html/wordpress/wp-content/themes
    owner: www-data
    group: www-data
    mode: 755
    type:
      - directory

hooks:
  ApplicationStop:
    - location: scripts/stop_apache.sh
      timeout: 60
      runas: root

  BeforeInstall:
    - location: scripts/clean_themes.sh
      timeout: 60
      runas: root

  AfterInstall:
    - location: scripts/deploy_themes.sh
      timeout: 120
      runas: root

  ApplicationStart:
    - location: scripts/restart_apache.sh
      timeout: 60
      runas: root