version: 0.0
os: linux

files:
  # Only deploy changed themes
  - source: /
    destination: /var/www/html/wordpress

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 180
      runas: root

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 180
      runas: root