version: 0.0
os: linux

files:
  - source: wp-content/themes/
    destination: /var/www/html/wordpress/wp-content/themes/

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 180
      runas: root

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 180
      runas: root