version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.1
    commands:
      - echo "Installing dependencies..."
      - apt-get update -y
      - apt-get install -y rsync zip unzip

  pre_build:
    commands:
      - echo "Preparing source code..."
      - echo "Detecting changed themes..."
      # Get changed theme folders from Git
      - if [ -d ".git" ]; then CHANGED_THEMES=$(git diff --name-only $CODEBUILD_RESOLVED_SOURCE_VERSION HEAD~1 | grep 'wp-content/themes/' | cut -d'/' -f4 | sort | uniq); fi
      - echo "Changed themes: $CHANGED_THEMES"

  build:
    commands:
      - echo "Zipping changed themes..."
      - for theme in $CHANGED_THEMES; do
          zip -r "themes/$theme.zip" "wp-content/themes/$theme";
        done

artifacts:
  files:
    - themes/*.zip

