version: 0.2

phases:
  build:
    commands:
      - echo "Creating direct deployment package..."
      - zip -r deployment.zip appspec.yml scripts/ wp-content/themes/

artifacts:
  files:
    - deployment.zip
  discard-paths: yes