version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - sudo apt-get update
      - sudo apt-get install -y rsync

  build:
    commands:
      - echo "Detecting changed themes..."
      - if [ -d ".git" ]; then CHANGED_THEMES=$(git diff --name-only $CODEBUILD_RESOLVED_SOURCE_VERSION | grep 'wp-content/themes/' | cut -d'/' -f4 | sort | uniq); else CHANGED_THEMES=$(ls wp-content/themes); fi
      - echo "Changed themes: $CHANGED_THEMES"

  post_build:
    commands:
      - echo "Preparing artifact..."
      - mkdir -p artifact/wp-content/themes
      
      # Copy appspec.yml to artifact root
      - cp appspec.yml artifact/
      
      # Copy scripts directory to artifact
      - cp -r scripts artifact/
      
      # Copy only changed themes
      - |
        for THEME in $CHANGED_THEMES; do
          if [ -d "wp-content/themes/$THEME" ]; then
            echo "Packing theme: $THEME"
            cp -r "wp-content/themes/$THEME" "artifact/wp-content/themes/"
          fi
        done
      
      # Verify what's being deployed
      - echo "Artifact contents:"
      - find artifact -type f | sort

artifacts:
  files:
    - '**/*'
  base-directory: artifact