version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - sudo apt install -y rsync || true

  build:
    commands:
      - echo "Detecting changed themes..."
      - CHANGED_THEMES=$(git diff --name-only $CODEBUILD_RESOLVED_SOURCE_VERSION | grep 'wp-content/themes/' | cut -d'/' -f4 | sort | uniq)

  post_build:
    commands:
      - echo "Preparing artifact for changed themes..."
      - mkdir -p artifact/wp-content/themes
      - |
        for THEME in $CHANGED_THEMES; do
          echo "Packing theme: $THEME"
          rsync -av wordpress/wp-content/themes/$THEME/ artifact/wp-content/themes/$THEME/
        done

artifacts:
  files:
    - '**/*'
  base-directory: artifact
  discard-paths: no