version: 0.2

phases:
  install:
    commands:
      - echo "Updating Ubuntu packages..."
      - apt-get update -y
      - apt-get install -y php php-cli php-mbstring php-mysql unzip zip rsync git

  pre_build:
    commands:
      - echo "Preparing source code..."
      - |
        echo "Detecting changed themes..."
        if [ -d ".git" ]; then
          CHANGED_THEMES=$(git diff --name-only $CODEBUILD_RESOLVED_SOURCE_VERSION HEAD~1 | grep 'wp-content/themes/' | cut -d'/' -f4 | sort | uniq)
        else
          CHANGED_THEMES=""
        fi
        echo "Changed themes: $CHANGED_THEMES"

  build:
    commands:
      - echo "Creating themes folder..."
      - mkdir -p themes
      - |
        if [ -n "$CHANGED_THEMES" ]; then
          for theme in $CHANGED_THEMES; do
            echo "Zipping theme: $theme"
            zip -r "themes/$theme.zip" "wp-content/themes/$theme"
          done
        else
          echo "No themes changed. Creating empty placeholder."
          touch themes/empty.txt
        fi

artifacts:
  files:
    - themes/*.zip
    - themes/empty.txt
    - appspec.yml