build:
  commands:
    - mkdir -p themes
    - |
      if [ -n "$CHANGED_THEMES" ]; then
        for theme in $CHANGED_THEMES; do
          zip -r "themes/$theme.zip" "wp-content/themes/$theme"
        done
      else
        echo "No themes changed. Creating placeholder."
        touch themes/empty.txt
      fi
artifacts:
  files:
    - appspec.yml
    - scripts/**
    - themes/*.zip
    - themes/empty.txt