version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - apt install -y zip

  build:
    commands:
      - echo "Creating deployment package..."
      - echo "Files to include:"
      - ls -la
      - zip -r deployment.zip appspec.yml scripts/ wp-content/themes/
      - echo "Verifying zip contents:"
      - unzip -l deployment.zip

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - wp-content/themes/**/*
  discard-paths: no