version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - apt-get update -y
      - apt-get install -y zip

  pre_build:
    commands:
      - echo "Pre-build phase..."

  build:
    commands:
      - echo "Building application..."
      - echo "Zipping theme folder and deployment scripts..."
      - zip -r wordpress-deploy.zip appspec.yml scripts/ wp-content/themes/

  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - wordpress-deploy.zip
  discard-paths: yes