version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - apt install -y zip

  build:
    commands:
      - echo "Zipping only theme folder and deployment scripts..."
      - zip -r wordpress-deploy.zip appspec.yml scripts wp-content/themes

artifacts:
  files:
    - wordpress-deploy.zip
    - scripts/**