version: 0.2

env:
  variables:
    TARGET_URL: "http://54.66.44.17/wordpress"
    S3_BUCKET: "zap-report-scan"

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - apt-get update -y
      - apt-get install -y jq docker awscli -q
      - echo "Pulling OWASP ZAP Docker image..."
      - docker pull ghcr.io/zaproxy/zaproxy:stable

  build:
    commands:
      - echo "Running OWASP ZAP baseline scan on $TARGET_URL ..."
      - |
        docker run --rm -v $(pwd):/zap/wrk/:rw ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
          -t "$TARGET_URL" -r zap_report.html -J zap_report.json || true

      - echo "Checking for high-risk alerts...."
      - |
        if [ -f zap_report.json ]; then
          HIGH=$(jq '.site[].alerts[] | select(.riskcode == "3") | .name' zap_report.json | wc -l)
          if [ "$HIGH" -gt 0 ]; then
            echo "⚠️ High risk vulnerabilities found: $HIGH"
          else
            echo "✅ No high-risk issues found."
          fi
        else
          echo "⚠️ zap_report.json not found — scan might have failed or produced no output."
        fi

  post_build:
    commands:
      - echo "Uploading ZAP HTML report to S3..."
      - REPORT_NAME="zap_report_$(date +%Y-%m-%d_%H-%M-%S).html"
      - if [ -f zap_report.html ]; then
          aws s3 cp zap_report.html s3://$S3_BUCKET/reports/$REPORT_NAME;
        else
          echo "⚠️ No zap_report.html found to upload.";
        fi
      - echo "ZAP scan completed successfully."

artifacts:
  files:
    - zap_report.html