version: 0.0
os: linux
files:
  - source: '*'  # The artifact contains only changed themes
    destination: /var/www/html/wordpress/wp-content/themes/

hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 180
      runas: ubuntu