version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies if any..."

  build:
    commands:
      - echo "Copying all WordPress themes..."
      - mkdir -p artifact/wp-content/themes
      - cp -r wp-content/themes/* artifact/wp-content/themes/

artifacts:
  files:
    - '**/*'
  base-directory: artifact