version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - sudo apt-get update
      - sudo apt-get install -y rsync || true

  build:
    commands:
      - echo "Detecting changed themes..."
      # Skip git diff if repo is shallow or CodeBuild source is not a git repo
      - if [ -d ".git" ]; then CHANGED_THEMES=$(git diff --name-only $CODEBUILD_RESOLVED_SOURCE_VERSION | grep 'wp-content/themes/' | cut -d'/' -f4 | sort | uniq); else CHANGED_THEMES=$(ls wp-content/themes); fi
      - echo Changed themes "$CHANGED_THEMES"

  post_build:
    commands:
      - echo "Preparing artifact for changed themes..."
      - mkdir -p artifact/wp-content/themes
      - |
        for THEME in $CHANGED_THEMES; do
          if [ -d "wp-content/themes/$THEME" ]; then
            echo "Packing theme: $THEME"
            rsync -av wp-content/themes/$THEME/ artifact/wp-content/themes/$THEME/
          fi
        done

artifacts:
  files:
    - '**/*'
  base-directory: artifact