version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - sudo yum update -y || true
      - sudo yum install -y zip unzip || true

  build:
    commands:
      - echo "Preparing WordPress themes artifact..."
      - mkdir -p artifact/wp-content/themes
      - cp -r wordpress/wp-content/themes/* artifact/wp-content/themes/ || echo "No themes found"

artifacts:
  files:
    - '**/*'
  base-directory: artifact
  discard-paths: no